export const PLAN_MBD = 1.8;
export const CURRENT_MBD = 1.67;
export const GAP_KBD = 130;

export const productionSeries = [
  { month: 'Jan 25', actual: 1.737, forecast: null },
  { month: 'Feb', actual: 1.67, forecast: null },
  { month: 'Mar', actual: 1.6, forecast: null },
  { month: 'Apr', actual: 1.68, forecast: null },
  { month: 'May', actual: 1.66, forecast: null },
  { month: 'Jun', actual: 1.7, forecast: null },
  { month: 'Jul', actual: 1.71, forecast: null },
  { month: 'Aug', actual: 1.63, forecast: null },
  { month: 'Sep', actual: 1.58, forecast: null },
  { month: 'Oct', actual: 1.597, forecast: null },
  { month: 'Nov', actual: 1.599, forecast: null },
  { month: 'Dec', actual: 1.544, forecast: null },
  { month: 'Jan 26', actual: 1.627, forecast: null },
  { month: 'Feb', actual: 1.484, forecast: null },
  { month: 'Mar', actual: 1.546, forecast: null },
  { month: 'Apr', actual: 1.663, forecast: null },
  { month: 'May', actual: 1.7, forecast: null },
  { month: 'Jun', actual: 1.735, forecast: null },
  { month: 'Jul', actual: 1.67, forecast: 1.67 },
  { month: 'Aug', actual: null, forecast: 1.71 },
  { month: 'Sep', actual: null, forecast: 1.75 },
  { month: 'Oct', actual: null, forecast: 1.79 },
  { month: 'Nov', actual: null, forecast: 1.81 },
  { month: 'Dec', actual: null, forecast: 1.82 },
];

export const liquidSplit2026 = [
  { month: 'Jan', crude: 1.459, condensate: 0.168, total: 1.627 },
  { month: 'Feb', crude: 1.314, condensate: 0.17, total: 1.484 },
  { month: 'Mar', crude: 1.371, condensate: 0.175, total: 1.546 },
  { month: 'Apr', crude: 1.482, condensate: 0.181, total: 1.663 },
  { month: 'May', crude: 1.523, condensate: 0.177, total: 1.7 },
  { month: 'Jun', crude: 1.56, condensate: 0.175, total: 1.735 },
  { month: 'Jul', crude: 1.505, condensate: 0.165, total: 1.67 },
];

export const terminals = [
  {
    name: 'Forcados',
    basin: 'Niger Delta',
    class: 'Onshore / shallow',
    jul: 322.34,
    jun: 306.36,
    plan: 340,
    quality: 'Reported',
  },
  {
    name: 'Bonny',
    basin: 'Niger Delta',
    class: 'Onshore / shallow',
    jul: 303.72,
    jun: 318.28,
    plan: 330,
    quality: 'Reported',
  },
  {
    name: 'Qua Iboe',
    basin: 'Niger Delta',
    class: 'Shallow water',
    jul: 158.02,
    jun: 164.73,
    plan: 175,
    quality: 'Reported',
  },
  {
    name: 'Escravos',
    basin: 'Niger Delta',
    class: 'Onshore / shallow',
    jul: 131.41,
    jun: 138.03,
    plan: 145,
    quality: 'Reported',
  },
  {
    name: 'Bonga',
    basin: 'Deepwater',
    class: 'FPSO',
    jul: 100.4,
    jun: 103.66,
    plan: 110,
    quality: 'Modeled sample',
  },
  {
    name: 'Egina',
    basin: 'Deepwater',
    class: 'FPSO',
    jul: 75.8,
    jun: 78.1,
    plan: 88,
    quality: 'Modeled sample',
  },
  {
    name: 'Erha',
    basin: 'Deepwater',
    class: 'FPSO',
    jul: 61.2,
    jun: 64.8,
    plan: 70,
    quality: 'Modeled sample',
  },
  {
    name: 'Agbami',
    basin: 'Deepwater',
    class: 'FPSO / condensate',
    jul: 58.7,
    jun: 57.9,
    plan: 62,
    quality: 'Modeled sample',
  },
  {
    name: 'Utapate',
    basin: 'Niger Delta',
    class: 'Onshore',
    jul: 55.3,
    jun: 51.4,
    plan: 60,
    quality: 'Modeled sample',
  },
  {
    name: 'Akpo',
    basin: 'Deepwater',
    class: 'FPSO / condensate',
    jul: 52.1,
    jun: 50.6,
    plan: 57,
    quality: 'Modeled sample',
  },
  {
    name: 'Brass River',
    basin: 'Niger Delta',
    class: 'Onshore / shallow',
    jul: 49.6,
    jun: 47.9,
    plan: 55,
    quality: 'Modeled sample',
  },
  {
    name: 'Usan',
    basin: 'Deepwater',
    class: 'FPSO',
    jul: 32.4,
    jun: 34.1,
    plan: 39,
    quality: 'Modeled sample',
  },
];

export const recoveryActions = [
  {
    rank: 1,
    action: 'Stabilize evacuation uptime',
    volume: 35,
    value: 0.86,
    timing: '30–60 days',
    confidence: 82,
    owner: 'Operations + JV',
    stage: 'Ready to mobilize',
    spend: '$',
    risk: 'Medium',
  },
  {
    rank: 2,
    action: 'Sequence maintenance windows',
    volume: 28,
    value: 0.69,
    timing: '60–90 days',
    confidence: 76,
    owner: 'Asset teams',
    stage: 'Decision ready',
    spend: '$',
    risk: 'Low',
  },
  {
    rank: 3,
    action: 'Well optimization campaign',
    volume: 22,
    value: 0.54,
    timing: '3–6 months',
    confidence: 71,
    owner: 'Subsurface',
    stage: 'Validate scope',
    spend: '$$',
    risk: 'Medium',
  },
  {
    rank: 4,
    action: 'Debottleneck terminal constraints',
    volume: 18,
    value: 0.44,
    timing: '4–8 months',
    confidence: 66,
    owner: 'Facilities',
    stage: 'Concept select',
    spend: '$$',
    risk: 'Medium',
  },
  {
    rank: 5,
    action: 'Reactivate shut-in well stock',
    volume: 42,
    value: 1.03,
    timing: '6–18 months',
    confidence: 58,
    owner: 'Development',
    stage: 'Stage-gate',
    spend: '$$$',
    risk: 'High',
  },
  {
    rank: 6,
    action: 'Accelerate tie-back candidates',
    volume: 55,
    value: 1.35,
    timing: '18–30 months',
    confidence: 49,
    owner: 'Major capital',
    stage: 'Appraise',
    spend: '$$$$',
    risk: 'High',
  },
];

export const globalProduction = [
  { country: 'United States', value: 23.612, rank: 1, region: 'Americas' },
  { country: 'Saudi Arabia', value: 11.214, rank: 2, region: 'Middle East' },
  { country: 'Russia', value: 10.535, rank: 3, region: 'Eurasia' },
  { country: 'Canada', value: 6.274, rank: 4, region: 'Americas' },
  { country: 'China', value: 5.446, rank: 5, region: 'Asia' },
  { country: 'Iran', value: 4.704, rank: 6, region: 'Middle East' },
  { country: 'Brazil', value: 4.655, rank: 7, region: 'Americas' },
  { country: 'Iraq', value: 4.5, rank: 8, region: 'Middle East' },
  {
    country: 'United Arab Emirates',
    value: 4.342,
    rank: 9,
    region: 'Middle East',
  },
  { country: 'Norway', value: 2.052, rank: 12, region: 'Europe' },
  { country: 'Nigeria', value: 1.675, rank: 15, region: 'Africa' },
  { country: 'Algeria', value: 1.404, rank: 16, region: 'Africa' },
  { country: 'Libya', value: 1.382, rank: 17, region: 'Africa' },
  { country: 'Angola', value: 1.059, rank: 18, region: 'Africa' },
];

export const forecastScenarios = [
  {
    name: 'Downside',
    probability: 25,
    q4: 1.6,
    valueRisk: 5.48,
    trigger: 'Renewed disruption; slower restart',
    color: '#b96049',
  },
  {
    name: 'Base',
    probability: 50,
    q4: 1.79,
    valueRisk: 0.27,
    trigger: 'Current ramp-up and uptime hold',
    color: '#147c69',
  },
  {
    name: 'Accelerated',
    probability: 25,
    q4: 1.88,
    valueRisk: 0,
    trigger: 'Priority actions land ahead of plan',
    color: '#c3943f',
  },
];

export const brentSeries = [
  { month: 'Jan 25', price: 79.27 },
  { month: 'Feb', price: 75.44 },
  { month: 'Mar', price: 72.73 },
  { month: 'Apr', price: 68.13 },
  { month: 'May', price: 64.45 },
  { month: 'Jun', price: 71.44 },
  { month: 'Jul', price: 71.04 },
  { month: 'Aug', price: 67.87 },
  { month: 'Sep', price: 67.99 },
  { month: 'Oct', price: 64.54 },
  { month: 'Nov', price: 63.8 },
  { month: 'Dec', price: 62.54 },
  { month: 'Jan 26', price: 66.6 },
  { month: 'Feb', price: 70.89 },
  { month: 'Mar', price: 103.13 },
  { month: 'Apr', price: 117.29 },
  { month: 'May', price: 107.14 },
  { month: 'Jun', price: 85.4 },
  { month: 'Jul', price: 83.76 },
  { month: 'Aug', price: 91.08 },
];

export const sources = [
  {
    source: 'NUPRC',
    dataset: 'July 2026 production release',
    coverage: 'National crude, condensate and leading terminals',
    cadence: 'Monthly',
    asOf: '12 Aug 2026',
    status: 'Current',
    type: 'Reported',
    href: 'https://www.nuprc.gov.ng/media/news/f89a978eca733d8947ae6c48',
  },
  {
    source: 'NUPRC',
    dataset: 'June 2026 production release',
    coverage: 'National trend and leading terminals',
    cadence: 'Monthly',
    asOf: '12 Jul 2026',
    status: 'Reconciled',
    type: 'Reported',
    href: 'https://nuprcdemo.nuprc.gov.ng/media/news/04290fca9f045a893c3daa9f',
  },
  {
    source: 'NUPRC',
    dataset: 'National Production Monitoring System',
    coverage: 'Production reporting methodology context',
    cadence: 'Operational',
    asOf: '2026',
    status: 'Reference',
    type: 'Method',
    href: 'https://www.nuprc.gov.ng/npms',
  },
  {
    source: 'EIA',
    dataset: 'Nigeria country analysis brief',
    coverage: 'Sector context, reserves, grades and disruptions',
    cadence: 'Periodic',
    asOf: '18 Nov 2025',
    status: 'Current',
    type: 'Reference',
    href: 'https://www.eia.gov/international/analysis/country/nga',
  },
  {
    source: 'EIA',
    dataset: 'International production rankings',
    coverage: 'Petroleum and other liquids by country',
    cadence: 'Annual',
    asOf: '2025',
    status: 'Current',
    type: 'Reported',
    href: 'https://www.eia.gov/international/rankings/country/COL?ev=false&f=A&pa=170&u=0&v=heatmap&y=01%2F01%2F2020',
  },
  {
    source: 'EIA',
    dataset: 'Europe Brent spot price',
    coverage: 'Monthly Brent spot price history',
    cadence: 'Monthly',
    asOf: 'Aug 2026',
    status: 'Current',
    type: 'Reported',
    href: 'https://www.eia.gov/dnav/pet/hist/leafhandler.ashx?f=m&n=pet&s=rbrte',
  },
  {
    source: 'Model',
    dataset: 'Executive planning case',
    coverage: '1.80 mb/d target and terminal allocations',
    cadence: 'Scenario',
    asOf: '06 Sep 2026',
    status: 'Assumption',
    type: 'Modeled',
    href: '/assumptions',
  },
  {
    source: 'Model',
    dataset: 'Recovery opportunity register',
    coverage: 'Action volume, timing, confidence and value',
    cadence: 'Scenario',
    asOf: '06 Sep 2026',
    status: 'Assumption',
    type: 'Modeled',
    href: '/assumptions',
  },
];

export const modelInputs = [
  {
    input: 'Executive planning case',
    value: '1.80 mb/d',
    owner: 'Portfolio planning',
    review: 'Monthly',
    classification: 'Modeled',
  },
  {
    input: 'Base oil price',
    value: '$75/bbl',
    owner: 'Finance',
    review: 'Monthly',
    classification: 'Scenario',
  },
  {
    input: 'Recovery realization',
    value: '90%',
    owner: 'Operations assurance',
    review: 'At stage-gate',
    classification: 'Scenario',
  },
  {
    input: 'Annual disruption days',
    value: '12 days',
    owner: 'Risk',
    review: 'Monthly',
    classification: 'Scenario',
  },
  {
    input: 'Forecast horizon',
    value: '90 days',
    owner: 'Planning',
    review: 'Monthly',
    classification: 'Modeled',
  },
  {
    input: 'Value basis',
    value: 'Gross, pre-take',
    owner: 'Finance',
    review: 'Quarterly',
    classification: 'Method',
  },
];

export function formatMoney(value: number) {
  if (value >= 1_000_000_000) return `$${(value / 1_000_000_000).toFixed(2)}bn`;
  return `$${(value / 1_000_000).toFixed(0)}m`;
}

export function monthlyExposure(gapKbd: number, price: number) {
  return gapKbd * 1000 * price * 30;
}
